//created on: 14 mar. 2022
package rules.cardiology;

//list any import classes here.
import pojos.Emergency;
import pojos.Location;
import pojos.Protocol;
import jdbc.SQLManager;

//declare any global variables here




rule "cardiology_heart_attack"
	dialect "java"
	when
	    dbm : SQLManager(  )
		u : Emergency (getDisease().getName().equals("Heart attack"))
	then
		u.setProtocol(dbm.Search_protocol_by_id(1));
		u.setSeverity(1);
		//System.out.println("AFTER:\n" + dbm.Search_stored_emergency_by_code(u.getCode()));
end

