//created on: 14 mar. 2022
package rules.toxicology;

//list any import classes here.
import pojos.Emergency;
import jdbc.SQLManager;


rule "food_poisoning"

	dialect "java"

	when
		dbm : SQLManager(  )
		u : Emergency (getDisease().getName().equals("Food poisoning"))
	then

		u.setSeverity(3);
		u.setProtocol(dbm.Search_protocol_by_id(7));
end



rule "drugs"

	dialect "java"

	when
		dbm : SQLManager(  )
		u : Emergency (getDisease().getName().equals("Drugs"))
	
	then

		u.setSeverity(2);
		u.setProtocol(dbm.Search_protocol_by_id(7));

end


rule "hangover"

	dialect "java"

	when
		dbm : SQLManager(  )
		u : Emergency (getDisease().getName().equals("Hangover"))
	
	then

		u.setSeverity(4);
		u.setProtocol(dbm.Search_protocol_by_id(7));

end


rule "medicament_allergy"

	dialect "java"

	when
		dbm : SQLManager(  )
		u : Emergency (getDisease().getName().equals("Medicament allergy"))
	
	then

		u.setSeverity(1);
		u.setProtocol(dbm.Search_protocol_by_id(7));

end





