//created on: 14 mar. 2022

//list any import classes here.
import pojos.Emergency;
import pojos.Location;
import pojos.Protocol;
import jdbc.SQLManager;


//declare any global variables here




rule "cardiology_heart_attack"
	dialect "java"
	when
	    dbm : SQLManager(  )
		//u : Emergency (getSpecialty().getName().equalsIgnoreCase("Heart attack"))
		u : Emergency (getSpecialty().getDisease().getDisease().equals("Heart attack")) // CONSIDERAR LOS SINTOMAS, SINO NO VA A FUNCIONAR --> NO SE PEUDE CONSIDERAR POR DISEASE PORQ ES NULL  --> LO ASOCIAMOS DESPUES
	then
		//u.getSpecialty().setDisease_list(dbm.getCardio_disease_list());
		u.getSpecialty().setDisease_list(dbm.getCardio_disease_list());
		u.setDisease(dbm.getCardio_disease_list().get(0));
		//u.setProtocol(u.getProtocol_list().get(0));
		//dbm.Update_emergency_info(u.getDirection(), u.setSeverity(1), u.getSpecialty().getId(), u.getLocation().getId(), dbm.getProtocol_list().get(0));
		dbm.Update_emergency_info(u.getDirection(), 1, u.getSpecialty().getId(), u.getLocation().getId(), 0, u.getId());
		System.out.println(dbm.Search_stored_emergency_by_code(u.getCode()));
end

