//created on: 14 mar. 2022
package rules.vehicleDisplay;

//list any import classes here.
import pojos.Emergency;
import pojos.Protocol;

/*
rule "severity_requires_transport"
	dialect "java"
	when
		u : Emergency (getSeverity() > 3)
	then
		u.getLocation().setVehicle(null);
end


rule "emergency_dont_require_transport"
	dialect "java"
	when
		u : Emergency (getProtocol().getProtocolType() == Protocol.Type.ADVICE)
	then
		u.getLocation().setVehicle(null);
end

rule "emergency_dont_require_transport"
	dialect "java"
	when
		u : Emergency (getProtocol().getId() == 1 )
	then
		u.getLocation().setVehicle(null);
end

*/